import sets
setA=sets.Set()
setA.add(5)
setA.add(4)
setA.add(3)
print("SetA:")
setA.__print__()
print(type(setA))
print (setA.size())
setA.remove(3)
setA.__print__()
print(setA.size())
print("")

print("odd:")
odd=sets.Set()
odd.add(1)
odd.add(3)
odd.add(5)
odd.add(7)
odd.add(9)
odd.add(11)
odd.__print__()
print("")

print("prime:")
prime=sets.Set()
prime.add(2)
prime.add(3)
prime.add(5)
prime.add(7)
prime.add(11)
prime.add(13)
prime.__print__()
print("")

print("odd-prime:")
odd_prime=odd.__subtract__(prime)
odd_prime.__print__()
print("")

print("prime-odd:")
prime_odd=prime.__subtract__(odd)
prime_odd.__print__()
print("")

odd.__print__()
prime.__print__()

print("Union:")
(prime.__union__(odd)).__print__()
(odd.__union__(prime)).__print__()
print("")

odd.__print__()
prime.__print__()

print("Intersection:")
(prime.__intersection__(odd)).__print__()
(odd.__intersection__(prime)).__print__()
